name: Build

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/erbium', 'lts/fermium', 'lts/gallium']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (Yarn)
        uses: bahmutov/npm-install@v1.7.12
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Build
        run: yarn build
