name: Test Code

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies (Yarn)
        uses: bahmutov/npm-install@v1.8.10
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Test
        run: yarn test:ci
